[[plugins]]
repo = 'Shougo/dein.vim'

# colorscheme
[[plugins]]
repo = 'tomasr/molokai'
hook_add = '''
  set background=dark
  au MyAutoCmd VimEnter * nested colorscheme molokai
'''

# toml syntax
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

# views
[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'Yggdroot/indentLine'

# neosnippet-snippets
[[plugins]]
repo = 'Shougo/neosnippet-snippets'
on_i = 1

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
  let g:ale_lint_on_text_changed=0
  let g:ale_lint_on_enter=0
  let g:ale_fix_on_save=1
  let g:ale_sign_column_always=1
  let g:ale_linters = {
    \ 'python': ['flake8'],
  \}
'''

[[plugins]]
repo = 'ervandew/supertab'
of_i = 1
