[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_source = '''
  let g:deoplete#enable_at_startup = 1
  inoremap <expr><tab> pumvisible() ? "\<C-n>" :
        \ neosnippet#expandable_or_jumpable() ?
        \    "\<Plug>(neosnippet_expand_or_jump)" : "\<tab>"
'''
hook_post_source = '''
  let g:deoplete#omni_patterns = {}
'''
on_i = 1
if = 'has("python3")'
if = 'has("nvim")'

[[plugins]]
repo = 'Shougo/neosnippet'
hook_source = '''
  imap <C-k> <Plug>(neosnippet_expand_or_jump)
  smap <C-k> <Plug>(neosnippet_expand_or_jump)
  xmap <C-k> <Plug>(neosnippet_expand_target)
  if has('conceal')
    set conceallevel=2 concealcursor=niv
  endif
'''
on_i  = 1
on_ft = ['snippet']
depends = ['neosnippet-snippets']

# python setting
# deoplete-jedi
[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = 'python'
hook_add = '''
  let g:deoplete#sources#jedi#python_path=system('echo -n $(which python3)')
  let g:python_host_prog=system('echo -n $(which python)')
  let g:python3_host_prog=system('echo -n $(which python3)')
'''

# pep8
[[plugins]]
repo = 'andviro/flake8-vim'
hook_add = '''
  let g:PyFlakeOnWrite = 1
  let g:PyFlakeCheckers = "pep8"
'''
[[plugins]]
repo = 'hynek/vim-python-pep8-indent'

[[plugins]]
repo = 'ervandew/supertab'
of_i = 1
